// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZl6M9K9GhKjqGxitATShlc9Ai3pPuWQY',
    appId: '1:896284499229:web:9f4e3875df33f347f855f4',
    messagingSenderId: '896284499229',
    projectId: 'ecommerce-a56d9',
    authDomain: 'ecommerce-a56d9.firebaseapp.com',
    storageBucket: 'ecommerce-a56d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANb8AulnBom2oYYgnEyPlHd1oayfEJ0DU',
    appId: '1:896284499229:android:e3d85c8ec02a4eaff855f4',
    messagingSenderId: '896284499229',
    projectId: 'ecommerce-a56d9',
    storageBucket: 'ecommerce-a56d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxaPqThSyt7kaYUA65V_FterHrY61RDZQ',
    appId: '1:896284499229:ios:6c9ce9e10719da74f855f4',
    messagingSenderId: '896284499229',
    projectId: 'ecommerce-a56d9',
    storageBucket: 'ecommerce-a56d9.appspot.com',
    iosBundleId: 'com.example.eccommerce4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxaPqThSyt7kaYUA65V_FterHrY61RDZQ',
    appId: '1:896284499229:ios:a117d0aca00c9317f855f4',
    messagingSenderId: '896284499229',
    projectId: 'ecommerce-a56d9',
    storageBucket: 'ecommerce-a56d9.appspot.com',
    iosBundleId: 'com.example.eccommerce4.RunnerTests',
  );
}
